#!/bin/bash

NAME="base"                                  # Name of the application
DJANGODIR=$HOME/base           # Django project directory
SOCKFILE=$HOME/base/run/gunicorn.sock  # we will communicte using this unix socket
USER=webadmin                                        # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=6                                   # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=app_project.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=app_project.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami` $HOME"

# Activate the virtual environment
cd $DJANGODIR
source bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR


echo "Starting $NAME as `whoami` $DJANGO_WSGI_MODULE"

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  #--bind=0.0.0.0 \
  --log-level=debug \
  --log-file=-
